# Generated by Django 6.0 on 2025-12-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('specialization', models.CharField(choices=[('ANXIETY', 'Anxiety'), ('DEPRESSION', 'Depression'), ('STRESS', 'Stress Management'), ('CAREER', 'Career Counselling'), ('RELATIONSHIP', 'Relationship Counselling'), ('GENERAL', 'General Counselling')], max_length=50)),
                ('experience_years', models.PositiveIntegerField()),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
