# Generated by Django 6.0 on 2025-12-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='last_admin_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
