# Generated by Django 6.0 on 2025-12-24 16:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corporates', '0001_initial'),
        ('psychologists', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('preferred_period', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('CUSTOM', 'Custom Range')], max_length=10)),
                ('preferred_time_start', models.TimeField(blank=True, null=True)),
                ('preferred_time_end', models.TimeField(blank=True, null=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], max_length=10)),
                ('payment_mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], max_length=10)),
                ('user_message', models.TextField(blank=True)),
                ('approved_slot_start', models.DateTimeField(blank=True, null=True)),
                ('approved_slot_end', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('alternate_slots', models.TextField(blank=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('email_verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('last_verification_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_token', models.UUIDField(blank=True, db_index=True, editable=False, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancellation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corporate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corporates.corporate')),
                ('psychologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psychologists.psychologist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.appuser')),
            ],
        ),
    ]
