# Generated by Django 6.0 on 2025-12-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferred_period',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('CUSTOM', 'Custom Range')], max_length=10, null=True),
        ),
    ]
