# Generated by Django 6.0 on 2025-12-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='cancellation_requested_at',
            new_name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancellation_token',
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('USER', 'User'), ('ADMIN', 'Admin')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
