# Generated by Django 6.0 on 2025-12-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_booking_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
