# Generated by Django 6.0 on 2025-12-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When admin approved the booking', null=True),
        ),
    ]
