# Generated by Django 6.0 on 2026-01-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_approved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cancellation_requested_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancellation_token',
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('USER', 'User'), ('ADMIN', 'Admin')], max_length=20, null=True),
        ),
    ]
