# Generated by Django 6.0 on 2026-01-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_remove_booking_cancellation_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_token',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
