# Generated by Django 6.0 on 2026-01-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_remove_booking_confirmation_token_booking_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approval_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='rejection_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
