# Generated by Django 6.0 on 2026-01-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_approval_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
